#include "test_context_module_cpp_impl.h"

#include <algorithm>

// Build-time-generated by logos-cpp-generator's umbrella pass. Defines
// `LogosModules` with one accessor per entry in metadata.json's
// `dependencies` list (plus the always-present `core_manager`). Because
// this module is `interface: "universal"`, mkLogosModule.nix passed
// `-DLOGOS_API_STYLE=std` to the codegen, so the wrapper signatures
// take/return std::string / std::vector / LogosMap / LogosList /
// int64_t / StdLogosResult throughout — no Qt at the call site. Only
// included on the .cpp side; the impl header stays out of the codegen's
// parse path.
#include "logos_sdk.h"

bool TestContextModuleCppImpl::wasContextReady() const {
    // Delegates to the SDK's first-class `isContextReady()`, which the
    // base class flips inside `_logosCoreSetContext_` right before the
    // `onContextReady()` hook fires. Used by the integration runner to
    // confirm the codegen-emitted provider's onInit actually wired the
    // context through. No need to override `onContextReady()` for a
    // separate counter — the SDK handles the "did the framework
    // populate me?" question.
    return isContextReady();
}

std::string TestContextModuleCppImpl::getModulePath() const {
    return modulePath();
}

std::string TestContextModuleCppImpl::getInstanceId() const {
    return instanceId();
}

std::string TestContextModuleCppImpl::getInstancePersistencePath() const {
    return instancePersistencePath();
}

bool TestContextModuleCppImpl::persistencePathEndsWith(const std::string& suffix) const {
    const std::string& p = instancePersistencePath();
    if (suffix.size() > p.size()) return false;
    return std::equal(suffix.rbegin(), suffix.rend(), p.rbegin());
}

// ── Cross-module calls via modules() ────────────────────────────────────────
//
// These exercise the entire chain the SDK is meant to enable for
// universal modules:
//
//   codegen-emitted onInit ─► std::make_unique<LogosModules>(api)
//          │
//          ▼
//   _logos_codegen_::maybeSetLogosModules(m_impl, &m_logosModules)
//          │
//          ▼  (resolved at compile time — opt-in via inheritance)
//   LogosModuleContext::_logosCoreSetLogosModulesPtr_(ptr)
//          │
//          ▼
//   m_impl.modules().<dep>.<method>(...)
//
// If any link in that chain is broken we get a runtime crash (null
// pointer) or a type error at compile time, both visible to the
// integration runner. The typed wrapper takes/returns Qt types
// (QString) because that's what the cpp-generator's client codegen
// emits today — the QString↔std::string bridge is the minimal price
// of admission and lives entirely in this .cpp.

std::string TestContextModuleCppImpl::callBasicEcho(const std::string& message) {
    // Pure-C++ cross-module call. Because this module is
    // `interface: "universal"`, the codegen emitted `TestBasicModule`
    // with std-typed signatures — `std::string echo(const std::string&)`
    // — and the umbrella's flat `LogosModules` exposes it as a single
    // accessor. No `.std.` nesting, no QString bridge.
    return modules().test_basic_module.echo(message);
}

int64_t TestContextModuleCppImpl::callBasicAddInts(int64_t a, int64_t b) {
    // The std-typed wrapper takes int64_t and narrows internally when
    // forwarding to the Qt-native `int addInts(int, int)` on the wire.
    // Caller passes 64-bit unconditionally — narrowing only matters
    // when the value exceeds int32, which the tests don't exercise.
    return modules().test_basic_module.addInts(a, b);
}

// ── Typed event subscriptions via the new `logos_events:` mechanism ────────
//
// This exercises the matching half of test_basic_module_cpp's
// `logos_events:` block: that module declares `testEvent(data: tstr)`
// and `multiArgEvent(name: tstr, count: int)`, ships a LIDL sidecar
// at `<lib>/share/logos/test_basic_module_cpp.lidl`, and the codegen
// generates typed `onTestEvent(...)` / `onMultiArgEvent(...)`
// accessors on the `TestBasicModuleCpp` wrapper that the consumer
// (this module) sees inside `LogosModules`. Callbacks here use
// std-typed args because this module's --api-style is `std`
// (config.interface == "universal"), matching the dep's wrapper for
// its std variant.

std::string TestContextModuleCppImpl::subscribeToBasicCppEvents() {
    bool okTest = modules().test_basic_module_cpp.onTestEvent(
        [this](const std::string& data) {
            m_lastTestEventData = data;
        });
    bool okMulti = modules().test_basic_module_cpp.onMultiArgEvent(
        [this](const std::string& name, int64_t count) {
            m_lastMultiArgName  = name;
            m_lastMultiArgCount = count;
        });
    return (okTest && okMulti) ? "ok" : "failed";
}

std::string TestContextModuleCppImpl::getLastTestEventData() {
    return m_lastTestEventData;
}

LogosMap TestContextModuleCppImpl::getLastMultiArgEvent() {
    LogosMap m;
    m["name"]  = m_lastMultiArgName;
    m["count"] = m_lastMultiArgCount;
    return m;
}
