#pragma once

// Integration smoke test for LogosModuleContext.
//
// The whole point of the SDK's LogosModuleContext base is that a
// universal-module impl can read the three runtime-injected properties
// (modulePath / instanceId / instancePersistencePath) and the per-build
// LogosModules aggregate WITHOUT ever touching the raw LogosAPI. This
// module proves that path works end-to-end by:
//
//   1. inheriting LogosModuleContext (opt-in mixin from the SDK)
//   2. exposing the four accessors through plain Q_INVOKABLE-style
//      methods that the codegen lifts into Qt glue
//   3. recording whether onContextReady() actually fired
//
// The host (logoscore --persistence-path <dir>) provisions a per-
// instance data directory under <dir>/test_context_module_cpp/<id>/
// before the module loads. The codegen-emitted onInit override copies
// those paths into the context base, so calling getInstancePersistencePath()
// over IPC must return a non-empty path rooted at <dir>. The
// integration runner in tests/run_tests.sh asserts exactly that.

#include <cstdint>
#include <string>

#include <logos_json.h>            // LogosMap (nlohmann::json alias)
#include <logos_module_context.h>  // the SDK mixin under test

class TestContextModuleCppImpl : public LogosModuleContext {
public:
    TestContextModuleCppImpl() = default;
    ~TestContextModuleCppImpl() = default;

    // ── Introspection methods (surfaced as Q_INVOKABLE by the codegen) ──

    // Returns whether the framework has populated the context — a
    // thin pass-through to the SDK's `isContextReady()` (which also
    // gates that the `onContextReady()` hook has fired). Should
    // always be `true` when the module is loaded by logoscore /
    // Basecamp; would be `false` only if the codegen onInit override
    // stopped calling LogosProviderBase::init -> onInit ->
    // LogosModuleContext::_logosCoreSetContext_ — i.e. the wire-up
    // we're testing.
    bool wasContextReady() const;

    // The three runtime-injected properties, surfaced verbatim. The
    // integration runner asserts:
    //   - modulePath != "" (host always sets it)
    //   - instanceId != ""
    //   - instancePersistencePath contains the persistence-path the
    //     caller passed to logoscore (we use a tmpdir per run, so the
    //     prefix is uniquely identifiable)
    std::string getModulePath() const;
    std::string getInstanceId() const;
    std::string getInstancePersistencePath() const;

    // Boolean variant of getInstanceId() — returns true iff the host
    // populated a non-empty instance ID. The CLI's `Result:` prefix
    // appears for any string return (including empty), so the
    // integration test asserts `Result: true` here to genuinely
    // distinguish "host wired the property" from "default-empty
    // fallback that any string getter would still produce".
    bool hasInstanceId() const;

    // Returns true iff `suffix` is a trailing substring of
    // instancePersistencePath(). Lets the integration test express
    // "the path ends with /test_context_module_cpp/<some-id>" without
    // having to compute the host-generated instance ID ahead of time.
    bool persistencePathEndsWith(const std::string& suffix) const;

    // ── Cross-module calls through modules() ────────────────────────────

    // Forwards to test_basic_module.echo(message) through the typed
    // wrapper LogosModules.test_basic_module — the integration runner
    // asserts that the round-trip returns the same string, proving the
    // codegen-emitted provider built a real LogosModules from the
    // host's LogosAPI, threaded it through LogosModuleContext, and
    // typed access via `modules()` resolves correctly.
    // The actual call site lives in the .cpp because this module is
    // `interface: "universal"` — the codegen emitted the dep wrapper
    // with std-typed signatures, and `modules()` requires the
    // generated `logos_sdk.h` to be complete in the TU. The .cpp
    // includes that header; the impl .h stays free of it so the
    // codegen parser sees only the C++ surface it expects.
    std::string callBasicEcho(const std::string& message);

    // Same chain, different shape — exercises an int-in/int-out method
    // so the test catches regressions in arg conversion specifically
    // (the Qt glue lowers int64_t ↔ int automatically, but only when
    // the cross-module call is wired the right way).
    int64_t callBasicAddInts(int64_t a, int64_t b);

    // ── Typed event subscriptions on a universal dep ────────────────────
    //
    // Registers typed callbacks on `test_basic_module_cpp`'s
    // `onTestEvent(...)` / `onMultiArgEvent(...)` accessors — both
    // generated by the codegen from the dep's `logos_events:` block via
    // the LIDL sidecar shipped with its headers. Each callback stores
    // the typed payload into instance state so the integration runner
    // can chain
    //   subscribe → trigger → read
    // in a single logoscore invocation (multi `-c`) and assert the
    // round-trip. Returns "ok" on successful registration; "failed"
    // if the underlying replica wasn't obtained.
    std::string subscribeToBasicCppEvents();

    // Last `testEvent(data)` payload captured by the subscription
    // callback. Empty string until the first event fires.
    std::string getLastTestEventData();

    // Last `multiArgEvent(name, count)` payload, packed as a
    // LogosMap so logoscore can format the wire-encoded result. Keys:
    //   "name"  -> std::string from the event
    //   "count" -> int64_t from the event
    // Empty map until the first event fires.
    LogosMap getLastMultiArgEvent();

private:
    // Captured event payloads from the test_basic_module_cpp
    // subscriptions set up in subscribeToBasicCppEvents(). The two
    // callbacks capture `[this]` and write through to these members.
    std::string m_lastTestEventData;
    std::string m_lastMultiArgName;
    int64_t     m_lastMultiArgCount = 0;
};
