//! Rust cdylib proxy — the Rust mirror of test_fullapi_proxy.
//!
//! Consumes the `full_api` surface of EITHER provider via an INTERFACE
//! dependency (full_api.lidl -> generated `full_api::FullApiClient`, bound to a
//! module name at runtime) and RE-EXPOSES the same surface: every method
//! forwards to the bound provider, every provider event is captured (and
//! re-emitted). useProvider(name) selects the runtime target; getLastEvent()
//! returns a short summary of the most recent forwarded event.
//!
//! The trait, the `full_api` client, emit_* emitters, and RustModuleContext are
//! generated by the builder from the contracts; the author writes only the impl.

use serde_json::Value;

include!(concat!(env!("CARGO_MANIFEST_DIR"), "/generated/provider_gen.rs"));

// Cross-thread state: event deliveries land on listener threads and are read
// back through the module's own methods. Mutex is imported by the scaffold.
static TARGET: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());
static LAST_EVENT: std::sync::Mutex<String> = std::sync::Mutex::new(String::new());

fn current_target() -> String {
    let t = TARGET.lock().unwrap().clone();
    if t.is_empty() { "test_fullapi_cpp".to_string() } else { t }
}

// Bind the interface to the current target and spawn one listener thread per
// event that captures a summary and re-emits the proxy's own event. Re-called on
// every useProvider(); old threads keep draining their (now-quiet) provider.
fn subscribe_to_target() {
    let target = current_target();
    macro_rules! listen {
        ($on:ident, $decode:ident, $e:ident => $summary:expr, $emit:expr) => {{
            let mut client = full_api::FullApiClient::bind(&target);
            if let Ok(sub) = client.$on() {
                std::thread::spawn(move || {
                    for ev in sub {
                        if let Some($e) = full_api::FullApiClient::$decode(&ev) {
                            *LAST_EVENT.lock().unwrap() = $summary;
                            $emit;
                        }
                    }
                });
            }
        }};
    }
    let arr_len = |v: &Value| v.as_array().map(|a| a.len()).unwrap_or(0);
    let obj_len = |v: &Value| v.as_object().map(|o| o.len()).unwrap_or(0);

    listen!(on_string_event, decode_string_event,
            e => format!("stringEvent:{}", e.v), emit_string_event(&e.v));
    listen!(on_bytes_event, decode_bytes_event,
            e => format!("bytesEvent:size={}", e.v.len()), emit_bytes_event(&e.v));
    listen!(on_int_event, decode_int_event,
            e => format!("intEvent:{}", e.v), emit_int_event(e.v));
    listen!(on_uint_event, decode_uint_event,
            e => format!("uintEvent:{}", e.v), emit_uint_event(e.v));
    listen!(on_double_event, decode_double_event,
            e => format!("doubleEvent:{}", e.v), emit_double_event(e.v));
    listen!(on_bool_event, decode_bool_event,
            e => format!("boolEvent:{}", e.v), emit_bool_event(e.v));
    listen!(on_any_event, decode_any_event,
            e => format!("anyEvent:{}", e.v), emit_any_event(&e.v));
    listen!(on_string_list_event, decode_string_list_event,
            e => format!("stringListEvent:size={}", arr_len(&e.v)), emit_string_list_event(&e.v));
    listen!(on_int_list_event, decode_int_list_event,
            e => format!("intListEvent:size={}", arr_len(&e.v)), emit_int_list_event(&e.v));
    listen!(on_uint_list_event, decode_uint_list_event,
            e => format!("uintListEvent:size={}", arr_len(&e.v)), emit_uint_list_event(&e.v));
    listen!(on_double_list_event, decode_double_list_event,
            e => format!("doubleListEvent:size={}", arr_len(&e.v)), emit_double_list_event(&e.v));
    listen!(on_bool_list_event, decode_bool_list_event,
            e => format!("boolListEvent:size={}", arr_len(&e.v)), emit_bool_list_event(&e.v));
    listen!(on_list_event, decode_list_event,
            e => format!("listEvent:size={}", arr_len(&e.v)), emit_list_event(&e.v));
    listen!(on_map_event, decode_map_event,
            e => format!("mapEvent:size={}", obj_len(&e.v)), emit_map_event(&e.v));
}

#[derive(Default)]
struct ProxyImpl;

// Every method binds a fresh client to the current target and forwards; the
// full_api client returns Result<_, LogosError>, so we default on transport
// error (the doctest asserts happy-path values).
impl TestFullapiProxyRustModule for ProxyImpl {
    fn on_context_ready(&mut self, _ctx: &RustModuleContext) {
        subscribe_to_target();
    }

    // ── Control ──────────────────────────────────────────────────────────────
    fn use_provider(&mut self, name: String) -> bool {
        *TARGET.lock().unwrap() = name;
        subscribe_to_target();
        true
    }
    fn current_provider(&mut self) -> String { current_target() }
    fn get_last_event(&mut self) -> String { LAST_EVENT.lock().unwrap().clone() }

    // ── Forwarded methods ────────────────────────────────────────────────────
    fn who_am_i(&mut self) -> String {
        full_api::FullApiClient::bind(&current_target()).who_am_i().unwrap_or_default()
    }
    fn echo_string(&mut self, v: String) -> String {
        full_api::FullApiClient::bind(&current_target()).echo_string(&v).unwrap_or_default()
    }
    fn echo_bytes(&mut self, v: Vec<u8>) -> Vec<u8> {
        full_api::FullApiClient::bind(&current_target()).echo_bytes(&v).unwrap_or_default()
    }
    fn echo_int(&mut self, v: i64) -> i64 {
        full_api::FullApiClient::bind(&current_target()).echo_int(v).unwrap_or(0)
    }
    fn echo_uint(&mut self, v: u64) -> u64 {
        full_api::FullApiClient::bind(&current_target()).echo_uint(v).unwrap_or(0)
    }
    fn echo_double(&mut self, v: f64) -> f64 {
        full_api::FullApiClient::bind(&current_target()).echo_double(v).unwrap_or(0.0)
    }
    fn echo_bool(&mut self, v: bool) -> bool {
        full_api::FullApiClient::bind(&current_target()).echo_bool(v).unwrap_or(false)
    }
    fn echo_any(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_any(&v).unwrap_or(Value::Null)
    }
    fn echo_string_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_string_list(&v).unwrap_or(Value::Null)
    }
    fn echo_int_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_int_list(&v).unwrap_or(Value::Null)
    }
    fn echo_uint_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_uint_list(&v).unwrap_or(Value::Null)
    }
    fn echo_double_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_double_list(&v).unwrap_or(Value::Null)
    }
    fn echo_bool_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_bool_list(&v).unwrap_or(Value::Null)
    }
    fn echo_list(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_list(&v).unwrap_or(Value::Null)
    }
    fn echo_map(&mut self, v: Value) -> Value {
        full_api::FullApiClient::bind(&current_target()).echo_map(&v).unwrap_or(Value::Null)
    }
    fn do_void(&mut self) -> Value {
        full_api::FullApiClient::bind(&current_target()).do_void().unwrap_or(Value::Null)
    }
    fn make_result(&mut self, ok: bool) -> Result<Value, String> {
        // The Rust client returns the provider's raw {success,value,error}
        // envelope as a Value (unlike the C++ client, which parses it into a
        // result struct). Unwrap it here so the proxy re-exposes the SAME result
        // shape as the provider (a single envelope), matching the C++ proxy.
        match full_api::FullApiClient::bind(&current_target()).make_result(ok) {
            Ok(v) => {
                if v.get("success").and_then(|s| s.as_bool()).unwrap_or(false) {
                    Ok(v.get("value").cloned().unwrap_or(Value::Null))
                } else {
                    Err(v.get("error").and_then(|e| e.as_str()).unwrap_or("error").to_string())
                }
            }
            Err(e) => Err(e.to_string()),
        }
    }

    // ── Forwarded event trigger drivers ──────────────────────────────────────
    fn fire_string_event(&mut self, v: String) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_string_event(&v).unwrap_or(false)
    }
    fn fire_bytes_event(&mut self, v: Vec<u8>) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_bytes_event(&v).unwrap_or(false)
    }
    fn fire_int_event(&mut self, v: i64) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_int_event(v).unwrap_or(false)
    }
    fn fire_uint_event(&mut self, v: u64) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_uint_event(v).unwrap_or(false)
    }
    fn fire_double_event(&mut self, v: f64) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_double_event(v).unwrap_or(false)
    }
    fn fire_bool_event(&mut self, v: bool) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_bool_event(v).unwrap_or(false)
    }
    fn fire_any_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_any_event(&v).unwrap_or(false)
    }
    fn fire_string_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_string_list_event(&v).unwrap_or(false)
    }
    fn fire_int_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_int_list_event(&v).unwrap_or(false)
    }
    fn fire_uint_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_uint_list_event(&v).unwrap_or(false)
    }
    fn fire_double_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_double_list_event(&v).unwrap_or(false)
    }
    fn fire_bool_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_bool_list_event(&v).unwrap_or(false)
    }
    fn fire_list_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_list_event(&v).unwrap_or(false)
    }
    fn fire_map_event(&mut self, v: Value) -> bool {
        full_api::FullApiClient::bind(&current_target()).fire_map_event(&v).unwrap_or(false)
    }
}

#[no_mangle]
pub extern "Rust" fn logos_module_install() {
    install::<ProxyImpl>();
}
