#include "full_api_veneer.h"

// GENERATED BY scratchpad/mkveneer.py from the two generated headers — the
// stand-in for what the real generator would emit. Every body is
// convert-args / delegate / convert-return; no conversion is written here.

bool FullApiVeneer::onStringEvent(std::function<void(const QString& v)> callback) {
    if (!callback) return false;
    return m_lp.onStringEvent([callback](const std::string& _a0) { callback(qtlp::fromStd<QString, std::string>(_a0)); });
}

bool FullApiVeneer::onBytesEvent(std::function<void(QByteArray v)> callback) {
    if (!callback) return false;
    return m_lp.onBytesEvent([callback](const std::vector<uint8_t>& _a0) { callback(qtlp::fromStd<QByteArray, std::vector<uint8_t>>(_a0)); });
}

bool FullApiVeneer::onIntEvent(std::function<void(qlonglong v)> callback) {
    if (!callback) return false;
    return m_lp.onIntEvent([callback](int64_t _a0) { callback(qtlp::fromStd<qlonglong, int64_t>(_a0)); });
}

bool FullApiVeneer::onUintEvent(std::function<void(qulonglong v)> callback) {
    if (!callback) return false;
    return m_lp.onUintEvent([callback](uint64_t _a0) { callback(qtlp::fromStd<qulonglong, uint64_t>(_a0)); });
}

bool FullApiVeneer::onDoubleEvent(std::function<void(double v)> callback) {
    if (!callback) return false;
    return m_lp.onDoubleEvent([callback](double _a0) { callback(qtlp::fromStd<double, double>(_a0)); });
}

bool FullApiVeneer::onBoolEvent(std::function<void(bool v)> callback) {
    if (!callback) return false;
    return m_lp.onBoolEvent([callback](bool _a0) { callback(qtlp::fromStd<bool, bool>(_a0)); });
}

bool FullApiVeneer::onAnyEvent(std::function<void(QVariant v)> callback) {
    if (!callback) return false;
    return m_lp.onAnyEvent([callback](const LogosMap& _a0) { callback(qtlp::fromStd<QVariant, LogosMap>(_a0)); });
}

bool FullApiVeneer::onStringListEvent(std::function<void(const QStringList& v)> callback) {
    if (!callback) return false;
    return m_lp.onStringListEvent([callback](const std::vector<std::string>& _a0) { callback(qtlp::fromStd<QStringList, std::vector<std::string>>(_a0)); });
}

bool FullApiVeneer::onIntListEvent(std::function<void(const QVariantList& v)> callback) {
    if (!callback) return false;
    return m_lp.onIntListEvent([callback](const LogosList& _a0) { callback(qtlp::fromStd<QVariantList, LogosList>(_a0)); });
}

bool FullApiVeneer::onUintListEvent(std::function<void(const QVariantList& v)> callback) {
    if (!callback) return false;
    return m_lp.onUintListEvent([callback](const LogosList& _a0) { callback(qtlp::fromStd<QVariantList, LogosList>(_a0)); });
}

bool FullApiVeneer::onDoubleListEvent(std::function<void(const QVariantList& v)> callback) {
    if (!callback) return false;
    return m_lp.onDoubleListEvent([callback](const LogosList& _a0) { callback(qtlp::fromStd<QVariantList, LogosList>(_a0)); });
}

bool FullApiVeneer::onBoolListEvent(std::function<void(const QVariantList& v)> callback) {
    if (!callback) return false;
    return m_lp.onBoolListEvent([callback](const LogosList& _a0) { callback(qtlp::fromStd<QVariantList, LogosList>(_a0)); });
}

bool FullApiVeneer::onListEvent(std::function<void(const QVariantList& v)> callback) {
    if (!callback) return false;
    return m_lp.onListEvent([callback](const LogosList& _a0) { callback(qtlp::fromStd<QVariantList, LogosList>(_a0)); });
}

bool FullApiVeneer::onMapEvent(std::function<void(const QVariantMap& v)> callback) {
    if (!callback) return false;
    return m_lp.onMapEvent([callback](const LogosMap& _a0) { callback(qtlp::fromStd<QVariantMap, LogosMap>(_a0)); });
}

bool FullApiVeneer::onTripleEvent(std::function<void(qlonglong i, const QString& s, QByteArray b)> callback) {
    if (!callback) return false;
    return m_lp.onTripleEvent([callback](int64_t _a0, const std::string& _a1, const std::vector<uint8_t>& _a2) { callback(qtlp::fromStd<qlonglong, int64_t>(_a0), qtlp::fromStd<QString, std::string>(_a1), qtlp::fromStd<QByteArray, std::vector<uint8_t>>(_a2)); });
}

QString FullApiVeneer::whoAmI(logos::CallError* err) {
    return qtlp::fromStd<QString, std::string>(m_lp.whoAmI(err));
}

QString FullApiVeneer::echoString(const QString& v, logos::CallError* err) {
    return qtlp::fromStd<QString, std::string>(m_lp.echoString(qtlp::toStd<std::string>(QVariant::fromValue(v)), err));
}

QByteArray FullApiVeneer::echoBytes(QByteArray v, logos::CallError* err) {
    return qtlp::fromStd<QByteArray, std::vector<uint8_t>>(m_lp.echoBytes(qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(v)), err));
}

qlonglong FullApiVeneer::echoInt(qlonglong v, logos::CallError* err) {
    return qtlp::fromStd<qlonglong, int64_t>(m_lp.echoInt(qtlp::toStd<int64_t>(QVariant::fromValue(v)), err));
}

qulonglong FullApiVeneer::echoUint(qulonglong v, logos::CallError* err) {
    return qtlp::fromStd<qulonglong, uint64_t>(m_lp.echoUint(qtlp::toStd<uint64_t>(QVariant::fromValue(v)), err));
}

double FullApiVeneer::echoDouble(double v, logos::CallError* err) {
    return qtlp::fromStd<double, double>(m_lp.echoDouble(qtlp::toStd<double>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::echoBool(bool v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.echoBool(qtlp::toStd<bool>(QVariant::fromValue(v)), err));
}

QVariant FullApiVeneer::echoAny(QVariant v, logos::CallError* err) {
    return qtlp::fromStd<QVariant, LogosMap>(m_lp.echoAny(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), err));
}

QStringList FullApiVeneer::echoStringList(const QStringList& v, logos::CallError* err) {
    return qtlp::fromStd<QStringList, std::vector<std::string>>(m_lp.echoStringList(qtlp::toStd<std::vector<std::string>>(QVariant::fromValue(v)), err));
}

QVariantList FullApiVeneer::echoIntList(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantList, LogosList>(m_lp.echoIntList(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

QVariantList FullApiVeneer::echoUintList(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantList, LogosList>(m_lp.echoUintList(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

QVariantList FullApiVeneer::echoDoubleList(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantList, LogosList>(m_lp.echoDoubleList(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

QVariantList FullApiVeneer::echoBoolList(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantList, LogosList>(m_lp.echoBoolList(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

QVariantList FullApiVeneer::echoList(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantList, LogosList>(m_lp.echoList(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

QVariantMap FullApiVeneer::echoMap(const QVariantMap& v, logos::CallError* err) {
    return qtlp::fromStd<QVariantMap, LogosMap>(m_lp.echoMap(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), err));
}

void FullApiVeneer::doVoid(logos::CallError* err) {
    m_lp.doVoid(err);
}

QString FullApiVeneer::echoTriple(qlonglong i, const QString& s, QByteArray b, logos::CallError* err) {
    return qtlp::fromStd<QString, std::string>(m_lp.echoTriple(qtlp::toStd<int64_t>(QVariant::fromValue(i)), qtlp::toStd<std::string>(QVariant::fromValue(s)), qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(b)), err));
}

LogosResult FullApiVeneer::makeResult(bool ok, logos::CallError* err) {
    return qtlp::fromStd<LogosResult, StdLogosResult>(m_lp.makeResult(qtlp::toStd<bool>(QVariant::fromValue(ok)), err));
}

bool FullApiVeneer::fireStringEvent(const QString& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireStringEvent(qtlp::toStd<std::string>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireBytesEvent(QByteArray v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireBytesEvent(qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireIntEvent(qlonglong v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireIntEvent(qtlp::toStd<int64_t>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireUintEvent(qulonglong v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireUintEvent(qtlp::toStd<uint64_t>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireDoubleEvent(double v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireDoubleEvent(qtlp::toStd<double>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireBoolEvent(bool v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireBoolEvent(qtlp::toStd<bool>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireAnyEvent(QVariant v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireAnyEvent(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireStringListEvent(const QStringList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireStringListEvent(qtlp::toStd<std::vector<std::string>>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireIntListEvent(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireIntListEvent(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireUintListEvent(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireUintListEvent(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireDoubleListEvent(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireDoubleListEvent(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireBoolListEvent(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireBoolListEvent(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireListEvent(const QVariantList& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireListEvent(qtlp::toStd<LogosList>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireMapEvent(const QVariantMap& v, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireMapEvent(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), err));
}

bool FullApiVeneer::fireTripleEvent(qlonglong i, const QString& s, QByteArray b, logos::CallError* err) {
    return qtlp::fromStd<bool, bool>(m_lp.fireTripleEvent(qtlp::toStd<int64_t>(QVariant::fromValue(i)), qtlp::toStd<std::string>(QVariant::fromValue(s)), qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(b)), err));
}

void FullApiVeneer::whoAmIAsync(std::function<void(QString)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.whoAmIAsync([callback](std::string _v) { callback(qtlp::fromStd<QString, std::string>(_v)); });
}

void FullApiVeneer::echoStringAsync(const QString& v, std::function<void(QString)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoStringAsync(qtlp::toStd<std::string>(QVariant::fromValue(v)), [callback](std::string _v) { callback(qtlp::fromStd<QString, std::string>(_v)); });
}

void FullApiVeneer::echoBytesAsync(QByteArray v, std::function<void(QByteArray)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoBytesAsync(qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(v)), [callback](std::vector<uint8_t> _v) { callback(qtlp::fromStd<QByteArray, std::vector<uint8_t>>(_v)); });
}

void FullApiVeneer::echoIntAsync(qlonglong v, std::function<void(qlonglong)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoIntAsync(qtlp::toStd<int64_t>(QVariant::fromValue(v)), [callback](int64_t _v) { callback(qtlp::fromStd<qlonglong, int64_t>(_v)); });
}

void FullApiVeneer::echoUintAsync(qulonglong v, std::function<void(qulonglong)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoUintAsync(qtlp::toStd<uint64_t>(QVariant::fromValue(v)), [callback](uint64_t _v) { callback(qtlp::fromStd<qulonglong, uint64_t>(_v)); });
}

void FullApiVeneer::echoDoubleAsync(double v, std::function<void(double)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoDoubleAsync(qtlp::toStd<double>(QVariant::fromValue(v)), [callback](double _v) { callback(qtlp::fromStd<double, double>(_v)); });
}

void FullApiVeneer::echoBoolAsync(bool v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoBoolAsync(qtlp::toStd<bool>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::echoAnyAsync(QVariant v, std::function<void(QVariant)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoAnyAsync(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), [callback](LogosMap _v) { callback(qtlp::fromStd<QVariant, LogosMap>(_v)); });
}

void FullApiVeneer::echoStringListAsync(const QStringList& v, std::function<void(QStringList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoStringListAsync(qtlp::toStd<std::vector<std::string>>(QVariant::fromValue(v)), [callback](std::vector<std::string> _v) { callback(qtlp::fromStd<QStringList, std::vector<std::string>>(_v)); });
}

void FullApiVeneer::echoIntListAsync(const QVariantList& v, std::function<void(QVariantList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoIntListAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](LogosList _v) { callback(qtlp::fromStd<QVariantList, LogosList>(_v)); });
}

void FullApiVeneer::echoUintListAsync(const QVariantList& v, std::function<void(QVariantList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoUintListAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](LogosList _v) { callback(qtlp::fromStd<QVariantList, LogosList>(_v)); });
}

void FullApiVeneer::echoDoubleListAsync(const QVariantList& v, std::function<void(QVariantList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoDoubleListAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](LogosList _v) { callback(qtlp::fromStd<QVariantList, LogosList>(_v)); });
}

void FullApiVeneer::echoBoolListAsync(const QVariantList& v, std::function<void(QVariantList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoBoolListAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](LogosList _v) { callback(qtlp::fromStd<QVariantList, LogosList>(_v)); });
}

void FullApiVeneer::echoListAsync(const QVariantList& v, std::function<void(QVariantList)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoListAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](LogosList _v) { callback(qtlp::fromStd<QVariantList, LogosList>(_v)); });
}

void FullApiVeneer::echoMapAsync(const QVariantMap& v, std::function<void(QVariantMap)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoMapAsync(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), [callback](LogosMap _v) { callback(qtlp::fromStd<QVariantMap, LogosMap>(_v)); });
}

void FullApiVeneer::doVoidAsync(std::function<void()> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.doVoidAsync([callback]() { callback(); });
}

void FullApiVeneer::echoTripleAsync(qlonglong i, const QString& s, QByteArray b, std::function<void(QString)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.echoTripleAsync(qtlp::toStd<int64_t>(QVariant::fromValue(i)), qtlp::toStd<std::string>(QVariant::fromValue(s)), qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(b)), [callback](std::string _v) { callback(qtlp::fromStd<QString, std::string>(_v)); });
}

void FullApiVeneer::makeResultAsync(bool ok, std::function<void(LogosResult)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.makeResultAsync(qtlp::toStd<bool>(QVariant::fromValue(ok)), [callback](StdLogosResult _v) { callback(qtlp::fromStd<LogosResult, StdLogosResult>(_v)); });
}

void FullApiVeneer::fireStringEventAsync(const QString& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireStringEventAsync(qtlp::toStd<std::string>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireBytesEventAsync(QByteArray v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireBytesEventAsync(qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireIntEventAsync(qlonglong v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireIntEventAsync(qtlp::toStd<int64_t>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireUintEventAsync(qulonglong v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireUintEventAsync(qtlp::toStd<uint64_t>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireDoubleEventAsync(double v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireDoubleEventAsync(qtlp::toStd<double>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireBoolEventAsync(bool v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireBoolEventAsync(qtlp::toStd<bool>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireAnyEventAsync(QVariant v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireAnyEventAsync(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireStringListEventAsync(const QStringList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireStringListEventAsync(qtlp::toStd<std::vector<std::string>>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireIntListEventAsync(const QVariantList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireIntListEventAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireUintListEventAsync(const QVariantList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireUintListEventAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireDoubleListEventAsync(const QVariantList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireDoubleListEventAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireBoolListEventAsync(const QVariantList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireBoolListEventAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireListEventAsync(const QVariantList& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireListEventAsync(qtlp::toStd<LogosList>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireMapEventAsync(const QVariantMap& v, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireMapEventAsync(qtlp::toStd<LogosMap>(QVariant::fromValue(v)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

void FullApiVeneer::fireTripleEventAsync(qlonglong i, const QString& s, QByteArray b, std::function<void(bool)> callback, Timeout /*timeout — LEAK 4*/) {
    if (!callback) return;
    m_lp.fireTripleEventAsync(qtlp::toStd<int64_t>(QVariant::fromValue(i)), qtlp::toStd<std::string>(QVariant::fromValue(s)), qtlp::toStd<std::vector<uint8_t>>(QVariant::fromValue(b)), [callback](bool _v) { callback(qtlp::fromStd<bool, bool>(_v)); });
}

// ── SPIKE PROBE (hand-written, not part of the generated surface) ────────────
//
// Option B: the same call with NO std intermediate. Everything else about the
// veneer is unchanged; only the hop through StdLogosResult is removed.
LogosResult FullApiVeneer::makeResultNoStdHop(bool ok, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(qtlp::toWire(QVariant::fromValue(ok)));
    return qtlp::fromWire<LogosResult>(m_state->client.invoke("makeResult", _args, err));
}
