// GENERATED BY logos-cpp-generator --api-style lp, then renamed FullApi -> FullApiLp.
//
//   logos-cpp-generator --metadata <this module>/metadata.json --general-only \
//     --api-style lp --interface full_api=interfaces/full_api.lidl
//
// Verbatim output apart from the class name (the Qt-typed generated `FullApi`
// occupies that name in this module). Checked in ONLY for the veneer spike: it
// is the wrapper the Qt veneer in full_api_veneer.h delegates to, so that the
// spike measures the REAL lp wrapper rather than a hand-written stand-in.
#pragma once
#include <cstdint>
#include <string>
#include <vector>
#include <functional>
#include <nlohmann/json.hpp>
#include "logos_json.h"
#include "logos_result.h"
#include "logos_call_error.h"
#include "logos_lp_client.h"

class FullApiLp {
public:
    struct State {
        logos::LpClient client;
        std::vector<logos::LpSubscription> subs;
        State(const std::string& target, const std::string& origin) : client(target, origin) {}
    };
    explicit FullApiLp(State* state) : m_state(state) {}

    bool onStringEvent(std::function<void(const std::string& v)> callback);
    bool onBytesEvent(std::function<void(const std::vector<uint8_t>& v)> callback);
    bool onIntEvent(std::function<void(int64_t v)> callback);
    bool onUintEvent(std::function<void(uint64_t v)> callback);
    bool onDoubleEvent(std::function<void(double v)> callback);
    bool onBoolEvent(std::function<void(bool v)> callback);
    bool onAnyEvent(std::function<void(const LogosMap& v)> callback);
    bool onStringListEvent(std::function<void(const std::vector<std::string>& v)> callback);
    bool onIntListEvent(std::function<void(const LogosList& v)> callback);
    bool onUintListEvent(std::function<void(const LogosList& v)> callback);
    bool onDoubleListEvent(std::function<void(const LogosList& v)> callback);
    bool onBoolListEvent(std::function<void(const LogosList& v)> callback);
    bool onListEvent(std::function<void(const LogosList& v)> callback);
    bool onMapEvent(std::function<void(const LogosMap& v)> callback);
    bool onTripleEvent(std::function<void(int64_t i, const std::string& s, const std::vector<uint8_t>& b)> callback);

    std::string whoAmI(logos::CallError* err = nullptr);
    void whoAmIAsync(std::function<void(std::string)> callback);
    std::string echoString(const std::string& v, logos::CallError* err = nullptr);
    void echoStringAsync(const std::string& v, std::function<void(std::string)> callback);
    std::vector<uint8_t> echoBytes(const std::vector<uint8_t>& v, logos::CallError* err = nullptr);
    void echoBytesAsync(const std::vector<uint8_t>& v, std::function<void(std::vector<uint8_t>)> callback);
    int64_t echoInt(int64_t v, logos::CallError* err = nullptr);
    void echoIntAsync(int64_t v, std::function<void(int64_t)> callback);
    uint64_t echoUint(uint64_t v, logos::CallError* err = nullptr);
    void echoUintAsync(uint64_t v, std::function<void(uint64_t)> callback);
    double echoDouble(double v, logos::CallError* err = nullptr);
    void echoDoubleAsync(double v, std::function<void(double)> callback);
    bool echoBool(bool v, logos::CallError* err = nullptr);
    void echoBoolAsync(bool v, std::function<void(bool)> callback);
    LogosMap echoAny(const LogosMap& v, logos::CallError* err = nullptr);
    void echoAnyAsync(const LogosMap& v, std::function<void(LogosMap)> callback);
    std::vector<std::string> echoStringList(const std::vector<std::string>& v, logos::CallError* err = nullptr);
    void echoStringListAsync(const std::vector<std::string>& v, std::function<void(std::vector<std::string>)> callback);
    LogosList echoIntList(const LogosList& v, logos::CallError* err = nullptr);
    void echoIntListAsync(const LogosList& v, std::function<void(LogosList)> callback);
    LogosList echoUintList(const LogosList& v, logos::CallError* err = nullptr);
    void echoUintListAsync(const LogosList& v, std::function<void(LogosList)> callback);
    LogosList echoDoubleList(const LogosList& v, logos::CallError* err = nullptr);
    void echoDoubleListAsync(const LogosList& v, std::function<void(LogosList)> callback);
    LogosList echoBoolList(const LogosList& v, logos::CallError* err = nullptr);
    void echoBoolListAsync(const LogosList& v, std::function<void(LogosList)> callback);
    LogosList echoList(const LogosList& v, logos::CallError* err = nullptr);
    void echoListAsync(const LogosList& v, std::function<void(LogosList)> callback);
    LogosMap echoMap(const LogosMap& v, logos::CallError* err = nullptr);
    void echoMapAsync(const LogosMap& v, std::function<void(LogosMap)> callback);
    void doVoid(logos::CallError* err = nullptr);
    void doVoidAsync(std::function<void()> callback);
    std::string echoTriple(int64_t i, const std::string& s, const std::vector<uint8_t>& b, logos::CallError* err = nullptr);
    void echoTripleAsync(int64_t i, const std::string& s, const std::vector<uint8_t>& b, std::function<void(std::string)> callback);
    StdLogosResult makeResult(bool ok, logos::CallError* err = nullptr);
    void makeResultAsync(bool ok, std::function<void(StdLogosResult)> callback);
    bool fireStringEvent(const std::string& v, logos::CallError* err = nullptr);
    void fireStringEventAsync(const std::string& v, std::function<void(bool)> callback);
    bool fireBytesEvent(const std::vector<uint8_t>& v, logos::CallError* err = nullptr);
    void fireBytesEventAsync(const std::vector<uint8_t>& v, std::function<void(bool)> callback);
    bool fireIntEvent(int64_t v, logos::CallError* err = nullptr);
    void fireIntEventAsync(int64_t v, std::function<void(bool)> callback);
    bool fireUintEvent(uint64_t v, logos::CallError* err = nullptr);
    void fireUintEventAsync(uint64_t v, std::function<void(bool)> callback);
    bool fireDoubleEvent(double v, logos::CallError* err = nullptr);
    void fireDoubleEventAsync(double v, std::function<void(bool)> callback);
    bool fireBoolEvent(bool v, logos::CallError* err = nullptr);
    void fireBoolEventAsync(bool v, std::function<void(bool)> callback);
    bool fireAnyEvent(const LogosMap& v, logos::CallError* err = nullptr);
    void fireAnyEventAsync(const LogosMap& v, std::function<void(bool)> callback);
    bool fireStringListEvent(const std::vector<std::string>& v, logos::CallError* err = nullptr);
    void fireStringListEventAsync(const std::vector<std::string>& v, std::function<void(bool)> callback);
    bool fireIntListEvent(const LogosList& v, logos::CallError* err = nullptr);
    void fireIntListEventAsync(const LogosList& v, std::function<void(bool)> callback);
    bool fireUintListEvent(const LogosList& v, logos::CallError* err = nullptr);
    void fireUintListEventAsync(const LogosList& v, std::function<void(bool)> callback);
    bool fireDoubleListEvent(const LogosList& v, logos::CallError* err = nullptr);
    void fireDoubleListEventAsync(const LogosList& v, std::function<void(bool)> callback);
    bool fireBoolListEvent(const LogosList& v, logos::CallError* err = nullptr);
    void fireBoolListEventAsync(const LogosList& v, std::function<void(bool)> callback);
    bool fireListEvent(const LogosList& v, logos::CallError* err = nullptr);
    void fireListEventAsync(const LogosList& v, std::function<void(bool)> callback);
    bool fireMapEvent(const LogosMap& v, logos::CallError* err = nullptr);
    void fireMapEventAsync(const LogosMap& v, std::function<void(bool)> callback);
    bool fireTripleEvent(int64_t i, const std::string& s, const std::vector<uint8_t>& b, logos::CallError* err = nullptr);
    void fireTripleEventAsync(int64_t i, const std::string& s, const std::vector<uint8_t>& b, std::function<void(bool)> callback);

private:
    State* m_state;  // umbrella-owned; the handle does not own it
};
