// GENERATED BY logos-cpp-generator --api-style lp, then renamed FullApi -> FullApiLp.
//
//   logos-cpp-generator --metadata <this module>/metadata.json --general-only \
//     --api-style lp --interface full_api=interfaces/full_api.lidl
//
// Verbatim output apart from the class name (the Qt-typed generated `FullApi`
// occupies that name in this module). Checked in ONLY for the veneer spike: it
// is the wrapper the Qt veneer in full_api_veneer.h delegates to, so that the
// spike measures the REAL lp wrapper rather than a hand-written stand-in.
#include "full_api_lp.h"
#include <nlohmann/json.hpp>

bool FullApiLp::onStringEvent(std::function<void(const std::string& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("stringEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_string() ? _a.at(0).get<std::string>() : std::string()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onBytesEvent(std::function<void(const std::vector<uint8_t>& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("bytesEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback(logos::jsonToBytes(_a.at(0)));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onIntEvent(std::function<void(int64_t v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("intEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_number_integer() ? _a.at(0).get<int64_t>() : (_a.at(0).is_number() ? static_cast<int64_t>(_a.at(0).get<double>()) : (int64_t)0)));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onUintEvent(std::function<void(uint64_t v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("uintEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_number_integer() ? _a.at(0).get<uint64_t>() : (_a.at(0).is_number() ? static_cast<uint64_t>(_a.at(0).get<double>()) : (uint64_t)0)));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onDoubleEvent(std::function<void(double v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("doubleEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_number() ? _a.at(0).get<double>() : 0.0));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onBoolEvent(std::function<void(bool v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("boolEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_boolean() ? _a.at(0).get<bool>() : false));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onAnyEvent(std::function<void(const LogosMap& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("anyEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback(_a.at(0));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onStringListEvent(std::function<void(const std::vector<std::string>& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("stringListEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback(logos::jsonToStringVec(_a.at(0)));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onIntListEvent(std::function<void(const LogosList& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("intListEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_array() ? _a.at(0) : LogosList::array()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onUintListEvent(std::function<void(const LogosList& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("uintListEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_array() ? _a.at(0) : LogosList::array()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onDoubleListEvent(std::function<void(const LogosList& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("doubleListEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_array() ? _a.at(0) : LogosList::array()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onBoolListEvent(std::function<void(const LogosList& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("boolListEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_array() ? _a.at(0) : LogosList::array()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onListEvent(std::function<void(const LogosList& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("listEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_array() ? _a.at(0) : LogosList::array()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onMapEvent(std::function<void(const LogosMap& v)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("mapEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 1) return;
        callback((_a.at(0).is_object() ? _a.at(0) : LogosMap::object()));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

bool FullApiLp::onTripleEvent(std::function<void(int64_t i, const std::string& s, const std::vector<uint8_t>& b)> callback) {
    if (!callback) return false;
    auto _sub = m_state->client.subscribe("tripleEvent", [callback](nlohmann::json _a) {
        if (!_a.is_array() || _a.size() < 3) return;
        callback((_a.at(0).is_number_integer() ? _a.at(0).get<int64_t>() : (_a.at(0).is_number() ? static_cast<int64_t>(_a.at(0).get<double>()) : (int64_t)0)), (_a.at(1).is_string() ? _a.at(1).get<std::string>() : std::string()), logos::jsonToBytes(_a.at(2)));
    });
    if (!_sub.valid()) return false;
    m_state->subs.push_back(std::move(_sub));
    return true;
}

std::string FullApiLp::whoAmI(logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    nlohmann::json _r = m_state->client.invoke("whoAmI", _args, err);
    return (_r.is_string() ? _r.get<std::string>() : std::string());
}

void FullApiLp::whoAmIAsync(std::function<void(std::string)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    m_state->client.invokeAsync("whoAmI", _args, [callback](nlohmann::json _r) {
        callback((_r.is_string() ? _r.get<std::string>() : std::string()));
    });
}

std::string FullApiLp::echoString(const std::string& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoString", _args, err);
    return (_r.is_string() ? _r.get<std::string>() : std::string());
}

void FullApiLp::echoStringAsync(const std::string& v, std::function<void(std::string)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoString", _args, [callback](nlohmann::json _r) {
        callback((_r.is_string() ? _r.get<std::string>() : std::string()));
    });
}

std::vector<uint8_t> FullApiLp::echoBytes(const std::vector<uint8_t>& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(logos::bytesToJson(v));
    nlohmann::json _r = m_state->client.invoke("echoBytes", _args, err);
    return logos::jsonToBytes(_r);
}

void FullApiLp::echoBytesAsync(const std::vector<uint8_t>& v, std::function<void(std::vector<uint8_t>)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(logos::bytesToJson(v));
    m_state->client.invokeAsync("echoBytes", _args, [callback](nlohmann::json _r) {
        callback(logos::jsonToBytes(_r));
    });
}

int64_t FullApiLp::echoInt(int64_t v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoInt", _args, err);
    return (_r.is_number_integer() ? _r.get<int64_t>() : (_r.is_number() ? static_cast<int64_t>(_r.get<double>()) : (int64_t)0));
}

void FullApiLp::echoIntAsync(int64_t v, std::function<void(int64_t)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoInt", _args, [callback](nlohmann::json _r) {
        callback((_r.is_number_integer() ? _r.get<int64_t>() : (_r.is_number() ? static_cast<int64_t>(_r.get<double>()) : (int64_t)0)));
    });
}

uint64_t FullApiLp::echoUint(uint64_t v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoUint", _args, err);
    return (_r.is_number_integer() ? _r.get<uint64_t>() : (_r.is_number() ? static_cast<uint64_t>(_r.get<double>()) : (uint64_t)0));
}

void FullApiLp::echoUintAsync(uint64_t v, std::function<void(uint64_t)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoUint", _args, [callback](nlohmann::json _r) {
        callback((_r.is_number_integer() ? _r.get<uint64_t>() : (_r.is_number() ? static_cast<uint64_t>(_r.get<double>()) : (uint64_t)0)));
    });
}

double FullApiLp::echoDouble(double v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoDouble", _args, err);
    return (_r.is_number() ? _r.get<double>() : 0.0);
}

void FullApiLp::echoDoubleAsync(double v, std::function<void(double)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoDouble", _args, [callback](nlohmann::json _r) {
        callback((_r.is_number() ? _r.get<double>() : 0.0));
    });
}

bool FullApiLp::echoBool(bool v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoBool", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::echoBoolAsync(bool v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoBool", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

LogosMap FullApiLp::echoAny(const LogosMap& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoAny", _args, err);
    return _r;
}

void FullApiLp::echoAnyAsync(const LogosMap& v, std::function<void(LogosMap)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoAny", _args, [callback](nlohmann::json _r) {
        callback(_r);
    });
}

std::vector<std::string> FullApiLp::echoStringList(const std::vector<std::string>& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoStringList", _args, err);
    return logos::jsonToStringVec(_r);
}

void FullApiLp::echoStringListAsync(const std::vector<std::string>& v, std::function<void(std::vector<std::string>)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoStringList", _args, [callback](nlohmann::json _r) {
        callback(logos::jsonToStringVec(_r));
    });
}

LogosList FullApiLp::echoIntList(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoIntList", _args, err);
    return (_r.is_array() ? _r : LogosList::array());
}

void FullApiLp::echoIntListAsync(const LogosList& v, std::function<void(LogosList)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoIntList", _args, [callback](nlohmann::json _r) {
        callback((_r.is_array() ? _r : LogosList::array()));
    });
}

LogosList FullApiLp::echoUintList(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoUintList", _args, err);
    return (_r.is_array() ? _r : LogosList::array());
}

void FullApiLp::echoUintListAsync(const LogosList& v, std::function<void(LogosList)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoUintList", _args, [callback](nlohmann::json _r) {
        callback((_r.is_array() ? _r : LogosList::array()));
    });
}

LogosList FullApiLp::echoDoubleList(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoDoubleList", _args, err);
    return (_r.is_array() ? _r : LogosList::array());
}

void FullApiLp::echoDoubleListAsync(const LogosList& v, std::function<void(LogosList)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoDoubleList", _args, [callback](nlohmann::json _r) {
        callback((_r.is_array() ? _r : LogosList::array()));
    });
}

LogosList FullApiLp::echoBoolList(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoBoolList", _args, err);
    return (_r.is_array() ? _r : LogosList::array());
}

void FullApiLp::echoBoolListAsync(const LogosList& v, std::function<void(LogosList)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoBoolList", _args, [callback](nlohmann::json _r) {
        callback((_r.is_array() ? _r : LogosList::array()));
    });
}

LogosList FullApiLp::echoList(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoList", _args, err);
    return (_r.is_array() ? _r : LogosList::array());
}

void FullApiLp::echoListAsync(const LogosList& v, std::function<void(LogosList)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoList", _args, [callback](nlohmann::json _r) {
        callback((_r.is_array() ? _r : LogosList::array()));
    });
}

LogosMap FullApiLp::echoMap(const LogosMap& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("echoMap", _args, err);
    return (_r.is_object() ? _r : LogosMap::object());
}

void FullApiLp::echoMapAsync(const LogosMap& v, std::function<void(LogosMap)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("echoMap", _args, [callback](nlohmann::json _r) {
        callback((_r.is_object() ? _r : LogosMap::object()));
    });
}

void FullApiLp::doVoid(logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    m_state->client.invoke("doVoid", _args, err);
}

void FullApiLp::doVoidAsync(std::function<void()> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    m_state->client.invokeAsync("doVoid", _args, [callback](nlohmann::json _r) {
        (void)_r; callback();
    });
}

std::string FullApiLp::echoTriple(int64_t i, const std::string& s, const std::vector<uint8_t>& b, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(i);
    _args.push_back(s);
    _args.push_back(logos::bytesToJson(b));
    nlohmann::json _r = m_state->client.invoke("echoTriple", _args, err);
    return (_r.is_string() ? _r.get<std::string>() : std::string());
}

void FullApiLp::echoTripleAsync(int64_t i, const std::string& s, const std::vector<uint8_t>& b, std::function<void(std::string)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(i);
    _args.push_back(s);
    _args.push_back(logos::bytesToJson(b));
    m_state->client.invokeAsync("echoTriple", _args, [callback](nlohmann::json _r) {
        callback((_r.is_string() ? _r.get<std::string>() : std::string()));
    });
}

StdLogosResult FullApiLp::makeResult(bool ok, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(ok);
    nlohmann::json _r = m_state->client.invoke("makeResult", _args, err);
    return logos::jsonToStdResult(_r);
}

void FullApiLp::makeResultAsync(bool ok, std::function<void(StdLogosResult)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(ok);
    m_state->client.invokeAsync("makeResult", _args, [callback](nlohmann::json _r) {
        callback(logos::jsonToStdResult(_r));
    });
}

bool FullApiLp::fireStringEvent(const std::string& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireStringEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireStringEventAsync(const std::string& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireStringEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireBytesEvent(const std::vector<uint8_t>& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(logos::bytesToJson(v));
    nlohmann::json _r = m_state->client.invoke("fireBytesEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireBytesEventAsync(const std::vector<uint8_t>& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(logos::bytesToJson(v));
    m_state->client.invokeAsync("fireBytesEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireIntEvent(int64_t v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireIntEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireIntEventAsync(int64_t v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireIntEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireUintEvent(uint64_t v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireUintEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireUintEventAsync(uint64_t v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireUintEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireDoubleEvent(double v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireDoubleEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireDoubleEventAsync(double v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireDoubleEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireBoolEvent(bool v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireBoolEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireBoolEventAsync(bool v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireBoolEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireAnyEvent(const LogosMap& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireAnyEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireAnyEventAsync(const LogosMap& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireAnyEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireStringListEvent(const std::vector<std::string>& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireStringListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireStringListEventAsync(const std::vector<std::string>& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireStringListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireIntListEvent(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireIntListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireIntListEventAsync(const LogosList& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireIntListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireUintListEvent(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireUintListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireUintListEventAsync(const LogosList& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireUintListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireDoubleListEvent(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireDoubleListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireDoubleListEventAsync(const LogosList& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireDoubleListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireBoolListEvent(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireBoolListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireBoolListEventAsync(const LogosList& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireBoolListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireListEvent(const LogosList& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireListEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireListEventAsync(const LogosList& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireListEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireMapEvent(const LogosMap& v, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    nlohmann::json _r = m_state->client.invoke("fireMapEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireMapEventAsync(const LogosMap& v, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(v);
    m_state->client.invokeAsync("fireMapEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

bool FullApiLp::fireTripleEvent(int64_t i, const std::string& s, const std::vector<uint8_t>& b, logos::CallError* err) {
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(i);
    _args.push_back(s);
    _args.push_back(logos::bytesToJson(b));
    nlohmann::json _r = m_state->client.invoke("fireTripleEvent", _args, err);
    return (_r.is_boolean() ? _r.get<bool>() : false);
}

void FullApiLp::fireTripleEventAsync(int64_t i, const std::string& s, const std::vector<uint8_t>& b, std::function<void(bool)> callback) {
    if (!callback) return;
    nlohmann::json _args = nlohmann::json::array();
    _args.push_back(i);
    _args.push_back(s);
    _args.push_back(logos::bytesToJson(b));
    m_state->client.invokeAsync("fireTripleEvent", _args, [callback](nlohmann::json _r) {
        callback((_r.is_boolean() ? _r.get<bool>() : false));
    });
}

